create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  segment text not null,
  company_name text,
  contact_name text,
  whatsapp text,
  instagram text,
  email text,
  plan text,
  posts_per_month integer default 0,
  reels_per_month integer default 0,
  monthly_value numeric default 0,
  due_day integer default 1,
  notes text,
  status text not null default 'ativo',
  voice_tone text,
  main_colors text,
  fonts text,
  audience text,
  services text,
  differentiators text,
  words_to_use text,
  words_to_avoid text,
  default_hashtags text,
  reference_links text,
  drive_folder text,
  brand_identity text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  client_id bigint references public.clients(id) on delete set null,
  content_type text not null,
  status text not null default 'ideia',
  priority text not null default 'media',
  created_at timestamptz not null default now(),
  due_date date,
  post_date date,
  owner text,
  description text,
  reference_links text,
  caption text,
  notes text,
  platform text,
  format text,
  approval_status text default 'nao_enviado',
  client_feedback text,
  sent_for_approval_at date,
  requested_changes text,
  approved_at date,
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at
before update on public.clients
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

alter table public.clients enable row level security;
alter table public.tasks enable row level security;
alter table public.settings enable row level security;

create policy "service role full access clients"
on public.clients for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role full access tasks"
on public.tasks for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role full access settings"
on public.settings for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
